name:                square-limit
version:             0.1.0.0
github:              "panaeon/square-limit"
license:             BSD3
author:              "vitalii voloshyn"
maintainer:          "vitalii.voloshyn@gmail.com"
copyright:           "vitalii voloshyn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/panaeon/square-limit#readme>

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - FlexibleInstances
  - FlexibleContexts
  - TypeApplications
  - RecordWildCards
  - ScopedTypeVariables
  - NoMonomorphismRestriction
  - TypeFamilies

dependencies:
- base-noprelude >= 4.7 && < 5
- relude
- containers
- text
- diagrams-lib
- diagrams
- diagrams-svg
- svg-tree

library:
  source-dirs: src

executables:
  square-limit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - square-limit

tests:
  square-limit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - square-limit
